export let headers = new Headers({
    'X-RapidAPI-Host': 'deezerdevs-deezer.p.rapidapi.com',
    'X-RapidAPI-Key': '54e83eebe2mshe9333423897dd0bp1e467cjsnd6cd0f6ca9c6',
  });

export let urlSearch = "https://striveschool-api.herokuapp.com/api/deezer/search?q=";
export let urlAlbum ="https://striveschool-api.herokuapp.com/api/deezer/album/";
export let urlArtista = "https://striveschool-api.herokuapp.com/api/deezer/artist/";

export let parole = [
    'Darkness',
    'Fire',
    'Sacrifice',
    'Warrior',
    'Blood',
    'Eternal',
    'Demon',
    'Steel',
    'Thunder',
    'Victory',
    'Shadow',
    'Rage',
    'Chaos',
    'Sorrow',
    'Crypt',
    'Storm',
    'Skull',
    'Battle',
    'Iron',
    'Witch',
    'Serpent',
    'Grave',
    'Angel',
    'Reaper',
    'Immortal',
    'Doom',
    'Nightmare',
    'Blade',
    'Raven',
    'Kingdom',
    'Mystic',
    'Abyss',
    'Torture',
    'Tempest',
    'Hate',
    'Crimson',
    'Throne',
    'Fear',
    'Twilight',
    'Beast',
    'Majesty',
    'Labyrinth',
    'Legacy',
    'Necropolis',
    'Whisper',
    'Hellfire',
    'Oracle',
    'Melody',
    'Harmony',
    'Echoes',
    'Wanderer',
    'Enchant',
    'Whisper',
    'Mystic',
    'Serenade',
    'Starlight',
    'Dreamer',
    'Embrace',
    'Ethereal',
    'Celestial',
    'Gentle',
    'Calm',
    'Tranquil',
    'Lullaby',
    'Radiance',
    'Breeze',
    'Infinite',
    'Harbor',
    'Peaceful',
    'Tranquility',
    'Soothing',
    'Reflection',
    'Serene',
    'Velvet',
    'Heavenly',
    'Grace',
    'Cascade',
    'Cherish',
    'Luminous',
    'Tender',
    'Harbour',
    'Glisten',
    'Cradle',
    'Whimsical',
    'Calmness',
    'Starlight',
    'Sylvan',
    'Luminescent',
    'Velvet',
    'Halcyon',
    'Pristine',
    'Enrapture',
    'Cerulean',
    'Silhouette'
];


export function sottoArray(arr, n) {
  let sottoArray = [];
  let arrClone = [...arr];
  for (let i = 0; i < n; i++) {
      sottoArray.push(arrClone.splice(Math.floor(Math.random() * arrClone.length), 1)[0]);  
  }    
  return sottoArray;  
}